/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    'service-providers': ServiceProvider;
    categories: Category;
    'sub-categories': SubCategory;
    'team-members': TeamMember;
    'blog-categories': BlogCategory;
    blog: Blog;
    'verify-providers': VerifyProvider;
    'verify-providers-email': VerifyProvidersEmail;
    'provider-reviews': ProviderReview;
    'provider-contacts': ProviderContact;
    'help-center-items': HelpCenterItem;
    pages: Page;
    users: User;
    'file-uploads': FileUpload;
    'image-uploads': ImageUpload;
    'remote-file-uploads': RemoteFileUpload;
    'contact-submissions': ContactSubmission;
    search: Search;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    'service-providers': ServiceProvidersSelect<false> | ServiceProvidersSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    'sub-categories': SubCategoriesSelect<false> | SubCategoriesSelect<true>;
    'team-members': TeamMembersSelect<false> | TeamMembersSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    blog: BlogSelect<false> | BlogSelect<true>;
    'verify-providers': VerifyProvidersSelect<false> | VerifyProvidersSelect<true>;
    'verify-providers-email': VerifyProvidersEmailSelect<false> | VerifyProvidersEmailSelect<true>;
    'provider-reviews': ProviderReviewsSelect<false> | ProviderReviewsSelect<true>;
    'provider-contacts': ProviderContactsSelect<false> | ProviderContactsSelect<true>;
    'help-center-items': HelpCenterItemsSelect<false> | HelpCenterItemsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    'file-uploads': FileUploadsSelect<false> | FileUploadsSelect<true>;
    'image-uploads': ImageUploadsSelect<false> | ImageUploadsSelect<true>;
    'remote-file-uploads': RemoteFileUploadsSelect<false> | RemoteFileUploadsSelect<true>;
    'contact-submissions': ContactSubmissionsSelect<false> | ContactSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  globals: {
    'main-navigation': MainNavigation;
    footer: Footer;
  };
  globalsSelect: {
    'main-navigation': MainNavigationSelect<false> | MainNavigationSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
  };
  locale: null;
  user: User & {
    collection: 'users';
  };
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-providers".
 */
export interface ServiceProvider {
  id: number;
  createdBy?: ('Admin' | 'Service provider') | null;
  /**
   * This field helps us figure out which providers are still in the process of registering their profile.
   */
  registrationProcessStatus?: ('In Progress' | 'Completed') | null;
  providerName: string;
  /**
   * This field is automatically generated from the company name. eg. My Company -> my-company
   */
  slug?: string | null;
  foundedYear?: number | null;
  logo?:
    | ({
        relationTo: 'image-uploads';
        value: number | ImageUpload;
      } | null)
    | ({
        relationTo: 'remote-file-uploads';
        value: number | RemoteFileUpload;
      } | null);
  providerShortDescription?: string | null;
  providerDescription?: string | null;
  websiteUrl?: string | null;
  email: string;
  phoneNumber?: string | null;
  telegramUsername?: string | null;
  socialMediaLinks?: {
    linkedin?: string | null;
    twitter?: string | null;
    youtube?: string | null;
    facebook?: string | null;
    instagram?: string | null;
    behance?: string | null;
    github?: string | null;
    customWeb?: string | null;
  };
  addresses?:
    | {
        addressType?: ('Headquarters' | 'Branch') | null;
        streetAddress1?: string | null;
        streetAddress2?: string | null;
        city?: string | null;
        state?: string | null;
        postalCode?: string | null;
        country?:
          | (
              | 'AD'
              | 'AE'
              | 'AF'
              | 'AG'
              | 'AI'
              | 'AL'
              | 'AM'
              | 'AO'
              | 'AQ'
              | 'AR'
              | 'AS'
              | 'AT'
              | 'AU'
              | 'AW'
              | 'AX'
              | 'AZ'
              | 'BA'
              | 'BB'
              | 'BD'
              | 'BE'
              | 'BF'
              | 'BG'
              | 'BH'
              | 'BI'
              | 'BJ'
              | 'BL'
              | 'BM'
              | 'BN'
              | 'BO'
              | 'BQ'
              | 'BR'
              | 'BS'
              | 'BT'
              | 'BV'
              | 'BW'
              | 'BY'
              | 'BZ'
              | 'CA'
              | 'CC'
              | 'CD'
              | 'CF'
              | 'CG'
              | 'CH'
              | 'CI'
              | 'CK'
              | 'CL'
              | 'CM'
              | 'CN'
              | 'CO'
              | 'CR'
              | 'CU'
              | 'CV'
              | 'CW'
              | 'CX'
              | 'CY'
              | 'CZ'
              | 'DE'
              | 'DJ'
              | 'DK'
              | 'DM'
              | 'DO'
              | 'DZ'
              | 'EC'
              | 'EE'
              | 'EG'
              | 'EH'
              | 'ER'
              | 'ES'
              | 'ET'
              | 'FI'
              | 'FJ'
              | 'FK'
              | 'FM'
              | 'FO'
              | 'FR'
              | 'GA'
              | 'GB'
              | 'GD'
              | 'GE'
              | 'GF'
              | 'GG'
              | 'GH'
              | 'GI'
              | 'GL'
              | 'GM'
              | 'GN'
              | 'GP'
              | 'GQ'
              | 'GR'
              | 'GS'
              | 'GT'
              | 'GU'
              | 'GW'
              | 'GY'
              | 'HK'
              | 'HM'
              | 'HN'
              | 'HR'
              | 'HT'
              | 'HU'
              | 'ID'
              | 'IE'
              | 'IL'
              | 'IM'
              | 'IN'
              | 'IO'
              | 'IQ'
              | 'IS'
              | 'IT'
              | 'JE'
              | 'JM'
              | 'JO'
              | 'JP'
              | 'KE'
              | 'KG'
              | 'KH'
              | 'KI'
              | 'KM'
              | 'KN'
              | 'KR'
              | 'KW'
              | 'KY'
              | 'KZ'
              | 'LA'
              | 'LB'
              | 'LC'
              | 'LI'
              | 'LK'
              | 'LR'
              | 'LS'
              | 'LT'
              | 'LU'
              | 'LV'
              | 'LY'
              | 'MA'
              | 'MC'
              | 'MD'
              | 'ME'
              | 'MF'
              | 'MG'
              | 'MH'
              | 'MK'
              | 'ML'
              | 'MM'
              | 'MN'
              | 'MO'
              | 'MP'
              | 'MQ'
              | 'MR'
              | 'MS'
              | 'MT'
              | 'MU'
              | 'MV'
              | 'MW'
              | 'MX'
              | 'MY'
              | 'MZ'
              | 'NA'
              | 'NC'
              | 'NE'
              | 'NF'
              | 'NG'
              | 'NI'
              | 'NL'
              | 'NO'
              | 'NP'
              | 'NR'
              | 'NU'
              | 'NZ'
              | 'OM'
              | 'PA'
              | 'PE'
              | 'PF'
              | 'PG'
              | 'PH'
              | 'PK'
              | 'PL'
              | 'PM'
              | 'PN'
              | 'PR'
              | 'PS'
              | 'PT'
              | 'PW'
              | 'PY'
              | 'QA'
              | 'RE'
              | 'RO'
              | 'RS'
              | 'RU'
              | 'RW'
              | 'SA'
              | 'SB'
              | 'SC'
              | 'SD'
              | 'SE'
              | 'SG'
              | 'SH'
              | 'SI'
              | 'SJ'
              | 'SK'
              | 'SL'
              | 'SM'
              | 'SN'
              | 'SO'
              | 'SR'
              | 'SS'
              | 'ST'
              | 'SV'
              | 'SX'
              | 'SY'
              | 'SZ'
              | 'TC'
              | 'TD'
              | 'TF'
              | 'TG'
              | 'TH'
              | 'TJ'
              | 'TK'
              | 'TL'
              | 'TM'
              | 'TN'
              | 'TO'
              | 'TR'
              | 'TT'
              | 'TV'
              | 'TW'
              | 'TZ'
              | 'UA'
              | 'UG'
              | 'UM'
              | 'US'
              | 'UY'
              | 'UZ'
              | 'VA'
              | 'VC'
              | 'VE'
              | 'VG'
              | 'VI'
              | 'VN'
              | 'VU'
              | 'WF'
              | 'WS'
              | 'XK'
              | 'YE'
              | 'YT'
              | 'ZA'
              | 'ZM'
              | 'ZW'
            )
          | null;
        id?: string | null;
      }[]
    | null;
  minimumBudget?: ('less_than_1k' | '1k_to_5k' | '5k_to_10k' | '10k_to_50k' | '50k_plus') | null;
  /**
   * Add case studies for this service provider
   */
  caseStudies?:
    | {
        clientName?: string | null;
        title?: string | null;
        budget?: ('less_than_1k' | '1k_to_5k' | '5k_to_10k' | '10k_to_50k' | '50k_plus') | null;
        timeline?: ('less_than_1_month' | '1_to_3_months' | '3_to_6_months' | '6_to_12_months' | '1_year_plus') | null;
        /**
         * This field is automatically generated from the project name. eg. My Project -> my-project
         */
        caseStudySlug?: string | null;
        description?: string | null;
        projectUrl?: string | null;
        files?:
          | (
              | {
                  relationTo: 'file-uploads';
                  value: number | FileUpload;
                }
              | {
                  relationTo: 'remote-file-uploads';
                  value: number | RemoteFileUpload;
                }
            )[]
          | null;
        images?:
          | (
              | {
                  relationTo: 'image-uploads';
                  value: number | ImageUpload;
                }
              | {
                  relationTo: 'remote-file-uploads';
                  value: number | RemoteFileUpload;
                }
            )[]
          | null;
        serviceCategories?: {
          /**
           * Select the service categories this case study belongs to
           */
          categories?: (number | Category)[] | null;
          /**
           * Select the sub-categories this case study belongs to
           */
          subCategories?: (number | SubCategory)[] | null;
        };
        achievedMetrics?:
          | {
              metric?: string | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  companySize?: ('1-10' | '11-50' | '51-200' | '201-500' | '501-1000' | '1001+') | null;
  /**
   * Add team members for this service provider
   */
  teamMembers?:
    | {
        firstName?: string | null;
        lastName?: string | null;
        position?: string | null;
        image?:
          | ({
              relationTo: 'image-uploads';
              value: number | ImageUpload;
            } | null)
          | ({
              relationTo: 'remote-file-uploads';
              value: number | RemoteFileUpload;
            } | null);
        id?: string | null;
      }[]
    | null;
  visibility?: {
    featured?: ('Yes' | 'No') | null;
    status?: ('Verified' | 'Unverified') | null;
    published?: ('Yes' | 'No') | null;
    waitingForModeration?: ('Yes' | 'No') | null;
  };
  categories?: {
    /**
     * Select the categories this service provider belongs to
     */
    categories?: (number | Category)[] | null;
    /**
     * Select the sub-categories this service provider belongs to
     */
    subCategories?: (number | SubCategory)[] | null;
  };
  findings?:
    | {
        title: string;
        text: string;
        id?: string | null;
      }[]
    | null;
  reviewsCount?: number | null;
  reviewsAverage?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-uploads".
 */
export interface ImageUpload {
  id: number;
  /**
   * The service provider this image belongs to
   */
  serviceProvider?: (number | null) | ServiceProvider;
  /**
   * Optional description of the image
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "remote-file-uploads".
 */
export interface RemoteFileUpload {
  id: number;
  /**
   * Type of the remote file
   */
  type: 'image' | 'document';
  /**
   * The service provider this file is associated with
   */
  serviceProvider?: (number | null) | ServiceProvider;
  /**
   * Remote file URL from our remote storage
   */
  remoteURL: string;
  /**
   * Optional description of the file
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "file-uploads".
 */
export interface FileUpload {
  id: number;
  /**
   * The service provider this file belongs to. Used during registration process for service provider.
   */
  serviceProvider?: (number | null) | ServiceProvider;
  /**
   * Optional description of the file
   */
  description?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * URL friendly version of a name used to identify a category
   */
  slug?: string | null;
  /**
   * When a category is displayed, this icon will be used
   */
  icon: string;
  subCategories?: (number | SubCategory)[] | null;
  /**
   * A short description of the category
   */
  description?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-categories".
 */
export interface SubCategory {
  id: number;
  name: string;
  /**
   * URL friendly version of a name used to identify a category
   */
  slug?: string | null;
  parentCategory: number | Category;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members".
 */
export interface TeamMember {
  id: number;
  name: string;
  position: string;
  image?: (number | null) | ImageUpload;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  slug: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog".
 */
export interface Blog {
  id: number;
  featuredImage?: (number | null) | ImageUpload;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  categories?: (number | null) | BlogCategory;
  relatedPosts?: (number | Blog)[] | null;
  content_html?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verify-providers".
 */
export interface VerifyProvider {
  id: number;
  firstName: string;
  lastName: string;
  workEmail: string;
  jobPosition: string;
  /**
   * Select the service provider this verification request is for
   */
  serviceProvider: number | ServiceProvider;
  note: string;
  /**
   * Status of the verification request
   */
  status?: ('Pending' | 'Approved' | 'Rejected') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verify-providers-email".
 */
export interface VerifyProvidersEmail {
  id: number;
  email: string;
  /**
   * 5-digit verification code sent to user's email
   */
  verificationCode: string;
  /**
   * Number of failed verification attempts
   */
  attempts?: number | null;
  /**
   * Maximum allowed verification attempts before code invalidation
   */
  maxAttempts?: number | null;
  /**
   * Status of the verification request
   */
  status?: ('Pending' | 'Verified' | 'Expired' | 'MaxAttemptsReached') | null;
  createdAt: string;
  /**
   * Verification code expiry timestamp (15 minutes from creation)
   */
  expiresAt?: string | null;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-reviews".
 */
export interface ProviderReview {
  id: number;
  /**
   * Select the service provider this review is for
   */
  serviceProvider: number | ServiceProvider;
  firstName: string;
  lastName: string;
  email: string;
  phoneNumber: string;
  telegramUsername: string;
  project: {
    description: string;
    budget: 'less_than_1k' | '1k_to_5k' | '5k_to_10k' | '10k_to_50k' | '50k_plus';
    timeline: 'less_than_1_month' | '1_to_3_months' | '3_to_6_months' | '6_to_12_months' | '1_year_plus';
    services: (
      | {
          relationTo: 'categories';
          value: number | Category;
        }
      | {
          relationTo: 'sub-categories';
          value: number | SubCategory;
        }
    )[];
    proofOfPaymentUrl?: string | null;
    file?:
      | ({
          relationTo: 'file-uploads';
          value: number | FileUpload;
        } | null)
      | ({
          relationTo: 'image-uploads';
          value: number | ImageUpload;
        } | null)
      | ({
          relationTo: 'remote-file-uploads';
          value: number | RemoteFileUpload;
        } | null);
  };
  review: {
    rating: number;
    review: string;
  };
  cashback: {
    crypto: 'BSC' | 'ERC-20';
    walletAddress: string;
  };
  status?: ('pending' | 'verified' | 'rejected') | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-contacts".
 */
export interface ProviderContact {
  id: number;
  /**
   * Select the service provider this review is for
   */
  serviceProvider: number | ServiceProvider;
  firstName: string;
  lastName: string;
  email: string;
  telegramUsername: string;
  project: {
    description: string;
    additionalDescription: string;
    budget: 'less_than_1k' | '1k_to_5k' | '5k_to_10k' | '10k_to_50k' | '50k_plus';
    timeline: 'less_than_1_month' | '1_to_3_months' | '3_to_6_months' | '6_to_12_months' | '1_year_plus';
    services: (
      | {
          relationTo: 'categories';
          value: number | Category;
        }
      | {
          relationTo: 'sub-categories';
          value: number | SubCategory;
        }
    )[];
    file?:
      | ({
          relationTo: 'file-uploads';
          value: number | FileUpload;
        } | null)
      | ({
          relationTo: 'image-uploads';
          value: number | ImageUpload;
        } | null)
      | ({
          relationTo: 'remote-file-uploads';
          value: number | RemoteFileUpload;
        } | null);
  };
  cashback: {
    crypto: 'BSC' | 'ERC-20';
    walletAddress: string;
  };
  status?: ('pending' | 'completed') | null;
  completedAt?: string | null;
  createdAt: string;
  updatedAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-center-items".
 */
export interface HelpCenterItem {
  id: number;
  title: string;
  content: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  richText?: {
    root: {
      type: string;
      children: {
        type: string;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name: string;
  role?: ('infrastructure' | 'admin' | 'editor' | 'client' | 'service_provider') | null;
  status?: ('pending' | 'active' | 'suspended' | 'deleted') | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions".
 */
export interface ContactSubmission {
  id: number;
  /**
   * First name of the contact
   */
  firstName: string;
  /**
   * Last name of the contact
   */
  lastName: string;
  /**
   * Work email address of the contact
   */
  workEmail: string;
  /**
   * Subject of the inquiry
   */
  subjectOfInquiry: string;
  /**
   * Message content
   */
  message: string;
  /**
   * Status of the contact submission
   */
  status?: ('new' | 'in-progress' | 'resolved' | 'archived') | null;
  /**
   * Internal notes about this contact submission
   */
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: number;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'service-providers';
    value: number | ServiceProvider;
  };
  searchableText?: string | null;
  region?: string | null;
  country?: string | null;
  companySize?: string | null;
  status?: string | null;
  categories?: string | null;
  subCategories?: string | null;
  minimumBudget?: string | null;
  reviewsAverage?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'service-providers';
        value: number | ServiceProvider;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'sub-categories';
        value: number | SubCategory;
      } | null)
    | ({
        relationTo: 'team-members';
        value: number | TeamMember;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'blog';
        value: number | Blog;
      } | null)
    | ({
        relationTo: 'verify-providers';
        value: number | VerifyProvider;
      } | null)
    | ({
        relationTo: 'verify-providers-email';
        value: number | VerifyProvidersEmail;
      } | null)
    | ({
        relationTo: 'provider-reviews';
        value: number | ProviderReview;
      } | null)
    | ({
        relationTo: 'provider-contacts';
        value: number | ProviderContact;
      } | null)
    | ({
        relationTo: 'help-center-items';
        value: number | HelpCenterItem;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'file-uploads';
        value: number | FileUpload;
      } | null)
    | ({
        relationTo: 'image-uploads';
        value: number | ImageUpload;
      } | null)
    | ({
        relationTo: 'remote-file-uploads';
        value: number | RemoteFileUpload;
      } | null)
    | ({
        relationTo: 'contact-submissions';
        value: number | ContactSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: number | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "service-providers_select".
 */
export interface ServiceProvidersSelect<T extends boolean = true> {
  createdBy?: T;
  registrationProcessStatus?: T;
  providerName?: T;
  slug?: T;
  foundedYear?: T;
  logo?: T;
  providerShortDescription?: T;
  providerDescription?: T;
  websiteUrl?: T;
  email?: T;
  phoneNumber?: T;
  telegramUsername?: T;
  socialMediaLinks?:
    | T
    | {
        linkedin?: T;
        twitter?: T;
        youtube?: T;
        facebook?: T;
        instagram?: T;
        behance?: T;
        github?: T;
        customWeb?: T;
      };
  addresses?:
    | T
    | {
        addressType?: T;
        streetAddress1?: T;
        streetAddress2?: T;
        city?: T;
        state?: T;
        postalCode?: T;
        country?: T;
        id?: T;
      };
  minimumBudget?: T;
  caseStudies?:
    | T
    | {
        clientName?: T;
        title?: T;
        budget?: T;
        timeline?: T;
        caseStudySlug?: T;
        description?: T;
        projectUrl?: T;
        files?: T;
        images?: T;
        serviceCategories?:
          | T
          | {
              categories?: T;
              subCategories?: T;
            };
        achievedMetrics?:
          | T
          | {
              metric?: T;
              id?: T;
            };
        id?: T;
      };
  companySize?: T;
  teamMembers?:
    | T
    | {
        firstName?: T;
        lastName?: T;
        position?: T;
        image?: T;
        id?: T;
      };
  visibility?:
    | T
    | {
        featured?: T;
        status?: T;
        published?: T;
        waitingForModeration?: T;
      };
  categories?:
    | T
    | {
        categories?: T;
        subCategories?: T;
      };
  findings?:
    | T
    | {
        title?: T;
        text?: T;
        id?: T;
      };
  reviewsCount?: T;
  reviewsAverage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  icon?: T;
  subCategories?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "sub-categories_select".
 */
export interface SubCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  parentCategory?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "team-members_select".
 */
export interface TeamMembersSelect<T extends boolean = true> {
  name?: T;
  position?: T;
  image?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog_select".
 */
export interface BlogSelect<T extends boolean = true> {
  featuredImage?: T;
  title?: T;
  slug?: T;
  content?: T;
  categories?: T;
  relatedPosts?: T;
  content_html?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verify-providers_select".
 */
export interface VerifyProvidersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  workEmail?: T;
  jobPosition?: T;
  serviceProvider?: T;
  note?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "verify-providers-email_select".
 */
export interface VerifyProvidersEmailSelect<T extends boolean = true> {
  email?: T;
  verificationCode?: T;
  attempts?: T;
  maxAttempts?: T;
  status?: T;
  createdAt?: T;
  expiresAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-reviews_select".
 */
export interface ProviderReviewsSelect<T extends boolean = true> {
  serviceProvider?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  phoneNumber?: T;
  telegramUsername?: T;
  project?:
    | T
    | {
        description?: T;
        budget?: T;
        timeline?: T;
        services?: T;
        proofOfPaymentUrl?: T;
        file?: T;
      };
  review?:
    | T
    | {
        rating?: T;
        review?: T;
      };
  cashback?:
    | T
    | {
        crypto?: T;
        walletAddress?: T;
      };
  status?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "provider-contacts_select".
 */
export interface ProviderContactsSelect<T extends boolean = true> {
  serviceProvider?: T;
  firstName?: T;
  lastName?: T;
  email?: T;
  telegramUsername?: T;
  project?:
    | T
    | {
        description?: T;
        additionalDescription?: T;
        budget?: T;
        timeline?: T;
        services?: T;
        file?: T;
      };
  cashback?:
    | T
    | {
        crypto?: T;
        walletAddress?: T;
      };
  status?: T;
  completedAt?: T;
  createdAt?: T;
  updatedAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "help-center-items_select".
 */
export interface HelpCenterItemsSelect<T extends boolean = true> {
  title?: T;
  content?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  richText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  role?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "file-uploads_select".
 */
export interface FileUploadsSelect<T extends boolean = true> {
  serviceProvider?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "image-uploads_select".
 */
export interface ImageUploadsSelect<T extends boolean = true> {
  serviceProvider?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "remote-file-uploads_select".
 */
export interface RemoteFileUploadsSelect<T extends boolean = true> {
  type?: T;
  serviceProvider?: T;
  remoteURL?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contact-submissions_select".
 */
export interface ContactSubmissionsSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  workEmail?: T;
  subjectOfInquiry?: T;
  message?: T;
  status?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  searchableText?: T;
  region?: T;
  country?: T;
  companySize?: T;
  status?: T;
  categories?: T;
  subCategories?: T;
  minimumBudget?: T;
  reviewsAverage?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-navigation".
 */
export interface MainNavigation {
  id: number;
  navItems?:
    | {
        title: string;
        /**
         * The slug of the page to link to
         */
        'page-slug'?: string | null;
        /**
         * Special menu that shows with list of all categories
         */
        'is-categories': 'yes' | 'no';
        categoryItems?:
          | {
              category: number | Category;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: number;
  navItems?:
    | {
        title: string;
        /**
         * The slug of the page to link to
         */
        slug: string;
        /**
         * Control visibility of the item in the footer without removing it
         */
        visible?: ('show' | 'hide') | null;
        id?: string | null;
      }[]
    | null;
  socials?:
    | {
        icon: string;
        link: string;
        /**
         * Control visibility of the item in the footer without removing it
         */
        visible?: ('show' | 'hide') | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "main-navigation_select".
 */
export interface MainNavigationSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        title?: T;
        'page-slug'?: T;
        'is-categories'?: T;
        categoryItems?:
          | T
          | {
              category?: T;
              id?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        title?: T;
        slug?: T;
        visible?: T;
        id?: T;
      };
  socials?:
    | T
    | {
        icon?: T;
        link?: T;
        visible?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}